global using DotNet8.CleanArchitectureWithUnitOfWork.Domain.Models.Blog;
global using DotNet8.CleanArchitectureWithUnitOfWork.Infrastructure.AppDbContextModels;
global using DotNet8.CleanArchitectureWithUnitOfWork.Domain.Interfaces;
global using DotNet8.CleanArchitectureWithUnitOfWork.Infrastructure.Repositories;
global using Microsoft.EntityFrameworkCore;