global using Microsoft.EntityFrameworkCore;
global using DotNet8.CleanArchitectureWithUnitOfWork.Domain.Interfaces;
global using Microsoft.Extensions.DependencyInjection;
global using DotNet8.CleanArchitectureWithUnitOfWork.Domain;
global using DotNet8.CleanArchitectureWithUnitOfWork.Domain.Models.Blog;
global using DotNet8.CleanArchitectureWithUnitOfWork.Infrastructure.AppDbContextModels;
